### ISSUE TITLE
[Bloquant] Création d'une entité

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/orleans-0218-projetio#175]
Je suis parti d'une base clean (juste une chargement de fixture).
Je me connecte en root
Si je créé une entité, j'arrive sur une page d'ajout des users qui ne me propose pas de user
Si je reviens à la page des entité, elle n'apparaît pas, mais elle est bien en base car je ne peux pas en recréer une du meme nom

**Comment by JuAlexandre** [comment]
C'est vrai que c'est pas très intuitif ...

En fait la liste des Entités ne liste que les Entités pour lesquelles l'utilisateur connecté à les droits d’accès.
Une fois l'Entité créée il faut éditer l'utilisateur et lui donner les droits sur l'Entité qu'on vient de créer.

**Comment by JuAlexandre** [comment]
PR #185
