### ISSUE TITLE
Suppression de page

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/orleans-0218-projetio#177]
Je ne sais pas trop pourquoi vous ne permettez l'effacement QUE de la dernière page. Mais si vous n'avez pas le choix, au moins faites en sorte que ce soit clair. 
Le plus simple c'est d'afficher le bouton uniquement sur la dernière page (voire en disabled sur les autres ?) 
Ou alors changer le label en "Supprimer la **dernière** page"
Sinon on pense supprimer la page 1 et on vire la 3, dangereux et pas ergo

**Comment by JuAlexandre** [comment]
PR #180
