### ISSUE TITLE
[UX]Bouton suppression page disabled

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/orleans-0218-projetio#193]
Pour le bouton suppression de page, c'est bien, il est disabled, par contre vous avez du toucher au cursor CSS par défaut. Normalement ça passe le cursor en "not-allowed", c'est plus parlant

Au passage tant que je suis sur les boutons, les "precedent" et "suivant" ont un pb d'alignement vertical (ou trop de padding bottom je ne sais pas).

**Comment by JuAlexandre** [comment]
PR #194

**Comment by jeromelegrand** [comment]
PR #199
