### ISSUE TITLE
Remove the .btn-sm from the "connexion/deconnexion" button

### ISSUE THREAD

**Issue by baptme** [WildCodeSchool/orleans-0218-projetio#214]
I prefer the text to be centered in the connect/disco. button in the navbar. You can either remove the .btn-sm class or work a way around to have it centered.

![bitmap](https://user-images.githubusercontent.com/1866964/42573927-b25d1ae4-851d-11e8-82bb-2c1ed56dd1f7.png)

**Comment by baptme** [comment]
or use the default bootstrap font, to have the .btn-sm working nicely
same issue as https://github.com/WildCodeSchool/orleans-0218-projetio/issues/216

**Comment by JuAlexandre** [comment]
#219
