### ISSUE TITLE
Variable Block Pull-Left for small screen

### ISSUE THREAD

**Issue by baptme** [WildCodeSchool/orleans-0218-projetio#224]
To avoid the variables box to cover the document. (open for discussion)

![image](https://user-images.githubusercontent.com/1866964/42581242-99b3dda2-852c-11e8-8458-c96b7051c70b.png)

![image](https://user-images.githubusercontent.com/1866964/42581393-efb8fd9a-852c-11e8-8c0f-e62ff378a388.png)

**Comment by jeromelegrand** [comment]
La position en dessous ne peut pas convenir sans grande modification du block. Celui-ci doit pouvoir se déployer comme sur la capture.
En revanche, en réduisant les marges et les padding, on peut atteindre une résolution de 1280px de large sans chevaucher le texte (capture). Cela te convient-il?
![capture du 2018-07-11 17-43-06](https://user-images.githubusercontent.com/20427810/42583939-6262df64-8532-11e8-8b41-5cee343b319d.png)

**Comment by baptme** [comment]
if you can use the same width for the WYSIWYG and the variables block it may looks just right. To avoid scrolling when you create a variable, the form with Nom/Type/Créer can go right up the div after Variables (+)
