### ISSUE TITLE
Created "Entités" not showing in "Entités" list

### ISSUE THREAD

**Issue by baptme** [WildCodeSchool/orleans-0218-projetio#227]
I've created the "Entités" aaa for test purpose.

![image](https://user-images.githubusercontent.com/1866964/42582154-b556840e-852e-11e8-9ef9-50e6618daabe.png)
![image](https://user-images.githubusercontent.com/1866964/42582174-c093d6be-852e-11e8-909a-11b7e634ac32.png)

**Comment by baptme** [comment]
Only showing when the entity is selected for at least one user.

**Comment by JuAlexandre** [comment]
It's voluntary, the user sees only the entities for which he has the rights.

Would you like to have the complete list of entities and only see the "Détails" and "Editer" buttons for the entities to which you have access ?

**Comment by baptme** [comment]
It would be nice to be able to select user to add to this new entity  then. If you try to create an entity and then add entity to each user, you will see what i mean. imagine 100+ users.

**Comment by jeromelegrand** [comment]
pr #245
